version: '3.7'
services:
  db:
    image: postgres:15
    container_name: production_control_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-docker
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production_control_system_app
    env_file:
      - .env-docker
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command:
      - "docker/app.sh"
    ports:
      - "7777:8000"

volumes:
  postgresdata:
