"""Added required tables

Revision ID: 05295271f3bc
Revises:
Create Date: 2024-02-11 13:04:15.272659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05295271f3bc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("closing_status", sa.Boolean(), nullable=True),
        sa.Column("shift_assignment", sa.String(), nullable=True),
        sa.Column("line", sa.String(), nullable=True),
        sa.Column("shift", sa.Integer(), nullable=True),
        sa.Column("brigade", sa.String(), nullable=True),
        sa.Column("lot_number", sa.Integer(), nullable=True),
        sa.Column("lot_date", sa.Date(), nullable=True),
        sa.Column("nomenclature", sa.String(), nullable=True),
        sa.Column("ekn_code", sa.String(), nullable=True),
        sa.Column("rc_identifier", sa.String(), nullable=True),
        sa.Column("shift_start", sa.DateTime(), nullable=True),
        sa.Column("shift_end", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_shifts_id"), "work_shifts", ["id"], unique=False)
    op.create_index(
        op.f("ix_work_shifts_lot_date"), "work_shifts", ["lot_date"], unique=False
    )
    op.create_index(
        op.f("ix_work_shifts_lot_number"), "work_shifts", ["lot_number"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("uin", sa.String(), nullable=False),
        sa.Column("is_aggregated", sa.Boolean(), nullable=True),
        sa.Column("aggregated_at", sa.DateTime(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lot"], ["work_shifts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uin"),
    )
    op.create_index(op.f("ix_products_uin"), "products", ["uin"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_uin"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_work_shifts_lot_number"), table_name="work_shifts")
    op.drop_index(op.f("ix_work_shifts_lot_date"), table_name="work_shifts")
    op.drop_index(op.f("ix_work_shifts_id"), table_name="work_shifts")
    op.drop_table("work_shifts")
    # ### end Alembic commands ###
